### ISSUE TITLE
study 파일 수정요청 사항

### ISSUE THREAD

**Issue by Hyunhans** [Hyunhans/practice_git-hub#1]
study.txt 파일에 line 9  수정 부탁드립니다:)

**Comment by feynthanku** [comment]
실수로 제가 해버렸으니 다시 고쳐놓을게여 ㅠㅅㅠ

**Comment by Hyunhans** [comment]
> 아니요! 
이거 고치고 close 해주신 다음에 ,
issue 로 다시 남겨주시며 좋을거 같은데요? ㅎㅎㅎㅎ

**Comment by ghost** [comment]
Line 9 수정완료했습니다. 고생많으셨습니다 :)
